const fs = require('fs');
const path = require('path');
const convict = require('convict');
require('dotenv').load();

convict.addFormat({
  name: 'path',
  // Check the existance
  validate: function (pathValue) {
    if (!fs.existsSync(pathValue) && !path.join(process.cwd(), pathValue)) {
      throw new Error('path cannot be found');
    }
  },
  // Return as absolute path if not yet
  coerce: function (pathValue) {
    if (!fs.existsSync(pathValue)) {
      return path.join(process.cwd(), pathValue);
    }
    return pathValue;
  }
});

const config = convict({
  drive: {
    keyFilePath: {
      doc: 'Path the key JSON file, generated by Google',
      default: '',
      format: 'path',
      env: 'DRIVE_KEY_FILE_PATH',
    },
    publicDir: {
      doc: 'Folder that is hosted by Mozaik server',
      default: path.join(process.cwd(), 'build'),
      format: 'path',
      env: 'MOZAIK_PUBLIC_DIR',
    }
  },
});

module.exports = config;
