const convict = require('convict')

const config = convict({
  drive: {
    keyFilePath: {
      doc: 'Path the key JSON file, generated by Google',
      default: '',
      format: String,
      env: 'DRIVE_KEY_FILE_PATH',
    },
  },
});

module.exports = config;
