const path = require('path');
const convict = require('convict');

const config = convict({
  drive: {
    keyFilePath: {
      doc: 'Path the key JSON file, generated by Google',
      default: '',
      format: String,
      env: 'DRIVE_KEY_FILE_PATH',
    },
    publicDir: {
      doc: 'Folder that is hosted by Mozaik server',
      default: path.join(process.cwd(), 'build'),
      format: String,
      env: 'MOZAIK_PUBLIC_DIR',
    }
  },
});

module.exports = config;
